version: "3.3"

services:
    wechat-service:
        privileged: true
        security_opt: # for attacking
            - seccomp:unconfined
        image: "chisbread/wechat-service:latest"
        restart: unless-stopped
        container_name: "wechat-service"
        environment:
            WC_AUTO_RESTART: "yes"
            DEMO_SERVICE: "yes" # Port 5555 will be occupied
            DEMO_AUTO_RESTART: "yes"
            INJMON_LOG_FILE: "/dev/null"
        ports:
            - "8080:8080" # noVNC
            - "5555:5555" # websocket server
        volumes:
            # are you bread?
            - "/home/bread/.wechat/WeChat Files/:/home/app/WeChat Files/" 
            - "/home/bread/.wechat/Applcation Data/:/home/app/.wine/drive_c/users/user/Application Data/"
            - "/home/bread/workspace/wechat-service/:/devel"
            - "/home/bread/external:/home/app/external"
        tty: true
